### ISSUE TITLE
Stop analysing rest sections if current section isn't a compressed section 

### ISSUE THREAD

**Issue by 913887524gsd** [n-eiling/cuda-fatbin-decompression#2]
First of all, nice work! I used to think that compressed section is agnostic to us,  but you did it!
When I'm playing with this program to analyse fatcubin generated by nvcc, I found that `depress` program just analyse the first section of fatcubin. After looking up your codes, I found the program will exit if it found that analysed section isn't a compressed section. It's not convenient when analysing a fatbinary contains multiple compute versions of cubin.
Maybe you shouldn't just exit so much early, just skip it and analysing rest sections.

**Comment by n-eiling** [comment]
You can find code that iterates over an entire Fatbin here: https://github.com/RWTH-ACS/cricket/blob/master/cpu/cpu-elf2.c#L445
The intention of this repo was more to test decompression in isolation. However, I am very open to contributions making this a more complete application.

**Comment by 913887524gsd** [comment]
OK, it's amazing to see that you have even done some reverse engineering about `.nv.info.*`, but I would like to use `cuobjdump` to analyse underlying kernel infomation for universality(although it will print many unrelated information, it's a headache problem). Maybe exploring the unknown is the romance of programmers.
Thanks a lot. :)

**Comment by n-eiling** [comment]
I actually did this as well for the same reasons you mention. I only recently changed the Cricket code to directly interpret the binary to remove the cuobjdump dependency and improve Performance. Here is some of the old code: https://github.com/RWTH-ACS/cricket/blob/e9b2c1c1834bedf815e5292e9eaada7f97fb5ea9/cpu/cpu-utils.c#L382
